"""empty message

Revision ID: 1f1d179d3efd
Revises: d02999819f26
Create Date: 2022-04-11 15:03:22.685171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1d179d3efd'
down_revision = 'd02999819f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('restaurantname', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_firstname'), 'users', ['firstname'], unique=True)
    op.create_index(op.f('ix_users_lastname'), 'users', ['lastname'], unique=True)
    op.create_index(op.f('ix_users_restaurantname'), 'users', ['restaurantname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_restaurantname'), table_name='users')
    op.drop_index(op.f('ix_users_lastname'), table_name='users')
    op.drop_index(op.f('ix_users_firstname'), table_name='users')
    op.drop_column('users', 'restaurantname')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
