"""empty message

Revision ID: 577efbd2a620
Revises: 93829d2f0727
Create Date: 2022-04-14 12:07:24.762661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577efbd2a620'
down_revision = '93829d2f0727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dish_posts_photo_key', 'dish_posts', type_='unique')
    op.drop_column('dish_posts', 'photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_posts', sa.Column('photo', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_unique_constraint('dish_posts_photo_key', 'dish_posts', ['photo'])
    # ### end Alembic commands ###
